[package]
name = "floodfill"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
tiff = { git = "https://github.com/Masterchef365/image-tiff", branch = "more_channels" }
anyhow = "1"
criterion = "0.3"

[profile.release]
debug = true

[[bench]]
name = "tiff"
harness = false
